### ISSUE TITLE
No more updates?

### ISSUE THREAD

**Issue by stastnypremysl** [urbanguacamole/torrent-paradise#14]
Why there are no more updates to the database? Is the project dead?

**Comment by urbanguacamole** [comment]
What database do you mean? IPFS or live website? The live website is updated in real time.

The index on IPFS must be rebuilt every once in a while. That can't be done by a cron job on the server, because there isn't enough RAM available and I'm too lazy to provision a server just for the rebuilding, so I run it every once in a while from my PC. I've just started a rebuild of the index for IPFS, should be live in an hour or two.

**Comment by stastnypremysl** [comment]
IPFS. How much RAM do you need for IPFS rebuild?

**Comment by urbanguacamole** [comment]
Oh, so RAM is probably not the bottleneck. Needs just under 2 GB, and I have upgraded the server since last trying this -- there is enough free RAM.

The IPFS reindexing process is single-core cpu perf bound, so it would fully utilize one of the two cpu cores on the current server. Long term average cpu usage on the server is ~150 %. I will setup the cronjob and set the process to very low priority so it doesn't steal any resources from users and set it to run once a month.

Thanks for the input!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by miigotu** [comment]
Last index update: 21/7/2020

**Comment by urbanguacamole** [comment]
@miigotu @stastnypremysl 

Should be fixed now, new IPFS index is rolling out now.
