### ISSUE TITLE
Feature request: Implementation of IPFS cluster 

### ISSUE THREAD

**Issue by stastnypremysl** [urbanguacamole/torrent-paradise#16]
I think, it would be really nice, if the DHT scrapping and IPNS website updates could be decentralized and everybody could run their own torrent-paradise server in the cluster.

It is true, that the website survive, when your servers are shuted down, but the DHT indexes will not be upgraded.

---
https://github.com/ipfs/ipfs-cluster

**Comment by urbanguacamole** [comment]
I thought about this for a really long time; in fact, this was initially the end goal of this project. But.

There would have to be nearly zero trust with other servers in the cluster to make it truly decentralized (keyword byzantine fault tolerance). How would you trust other servers in the cluster with their seed/leech counts? What if one of them tries to push their own fake torrents?

I couldn't come up with anything else than some kind of Proof of Work system that would make the system very expensive to run  and not economically viable, since the income from clearweb ads covers hosting only in part. PoS is also not possible, since there is no value that this system could distribute as rewards -- where would this value come from? Sponsors? Me? :)

This is why I settled on the answer that if I get hit by a bus tomorrow, the indices will live on IPFS until someone uses my open source code and starts from my index dump, adding new torrents to the website over time and eventually gains users trust. And the project will, hopefully, live on in one form or another

If you have some more ideas about how to make this decentralized, feel free to elaborate.

Closed (for now?)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by stastnypremysl** [comment]
We don't need fully decentralized solution. My idea:

The network could be made of nodes which will be assigned Tier rank. Tier 0 rank would be root servers, Tier 1 trusted, Tier 2 arbitrary. The verification system would be GPG based (peer revised servers). 

Everybody can make a server, but every other node would decide the tier of server using GPG.

You would have a Tier 0 key, which would be default in the software, and you could decide whether the server is trustworthy and how much using the stability and validity of provided server data in time.

Tier 0 servers - the servers with access to DNS records and IPNS keys.

Tier 1 servers - the servers which are gathering non-verifiable torrent information.

Tier 2 servers - the servers which are gathering information, that can be easily verified by Tier 1 servers. (for example seeders and peers with dedicated ip address)

The best part is, that anybody can make their tier 0 keys for their own servers and use the rest of the network as they please. So torrent-paradise could became a widely used backend for DHT torrent websites.

What do you think about it?

**Comment by urbanguacamole** [comment]
Maybe I just don't believe in the generosity of humanity enough, but what incentives are there for Tier 1/2 server operators? This would save a negligible amount of server resources (by not having to update all seed/leech counts) and complicate things hugely. The data would not be that much more fresh. The project (DNS,IPNS) would still die with me if I get hit by a bus.

Most importantly, what's the goal here? To decentralize the server costs (which are already low) or remove all SPOF?

Sorry for the late reply, just found this draft.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
