### ISSUE TITLE
Bug: Wrong TXT record in DNS

### ISSUE THREAD

**Issue by stastnypremysl** [urbanguacamole/torrent-paradise#17]
When I drill TXT torrent-paradise.ml I get 
dnslink=/ipfs/QmZieTrQwQgi8AKH94b1Sck8j1NTtFExRJggdiKZhpekJ9/

The website is therefore not updated on the address /ipns/torrent-paradise.ml/. 

I think, it would be better, if you set the dnslink to 
dnslink=/ipns/12D3KooWB3GY1u6zMLqnf3MJ8zhX3SS1oBj7VXk3xp6sJJiFGZXp

**Comment by urbanguacamole** [comment]
Good catch! The reason it is set up the way it is is that IPFS lookups are significantly faster than IPNS lookups. Compare: https://cloudflare-ipfs.com/ipns/12D3KooWB3GY1u6zMLqnf3MJ8zhX3SS1oBj7VXk3xp6sJJiFGZXp/ and https://cloudflare-ipfs.com/ipfs/QmQMqzGEcUDVeps9n39ffdvKguXLZ3AU6CjCMiw5HjvKd3/.

This gap got even wider with the recent IPFS update that sped up IPFS even more.

IMO the problem is that the script I use to update IPFS does not update the DNSLink record to the new IPFS address, will fix.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
