### ISSUE TITLE
Adding date uploaded on torrent search

### ISSUE THREAD

**Issue by fahadalisarwar1** [urbanguacamole/torrent-paradise#20]
The search results doesn't show when the torrent was uploaded/updated. I think it will be good idea to add datetime information into search results. This would help in filtering out older torrents

**Comment by urbanguacamole** [comment]
That's because there is no date created in torrent metadata. I have saved date discovered internally, but since the site is 1,5 yrs old, the oldest torrent would be that old.

I plan on adding this feature in a few years when it would make sense

Close #20

-------- Původní zpráva --------
Zapnuto 25. 7. 2020 22:01, Fahad Ali Sarwar < notifications@github.com> napsal:
The search results doesn't show when the torrent was uploaded/updated. I think it will be good idea to add datetime information into search results. This would help in filtering out older torrents
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[https://github.com](<a href=)/urbanguacamole/torrent-paradise/issues/20">https://github.com/urbanguacamole/torrent-paradise/issues/20", "url": "[https://github.com](<a href=)/urbanguacamole/torrent-paradise/issues/20">https://github.com/urbanguacamole/torrent-paradise/issues/20", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by fahadalisarwar1** [comment]
Makes sense. Thank you.
