### ISSUE TITLE
Domain not resolving

### ISSUE THREAD

**Issue by ProgrammerWhoPrograms** [urbanguacamole/torrent-paradise#45]
Could you please post an IP address on the site and here so we can add it to /etc/hosts?
Is this censorship by registr{ie,ar}s or is it just part of the name change?

**Comment by zzggbb** [comment]
in the meantime, you can go to this url to access torrent-paradise.ml:

https://cloudflare-ipfs.com/ipfs/QmQjsKamNFZRvCMXDvZXQmRYjsmSkmZG5pBCTY4LtMj8hs/index.html

**Comment by 3unjee** [comment]
Unfortunately the api does not work with the ipfs version.

**Comment by kubo6472** [comment]
It looks like the site has experienced a hostile takeover and now redirects to advertisement scam sites.

**Comment by pmorch** [comment]
Is there an /ipns/ URL also what one could bookmark, so that we're not stuck on this particular cid/revision of the website?

**Comment by kubo6472** [comment]
> Is there an /ipns/ URL also what one could bookmark, so that we're not stuck on this particular cid/revision of the website?

Hey, check README :D https://github.com/urbanguacamole/torrent-paradise/blob/master/README.md?plain=1#L4

**Comment by pmorch** [comment]
Hi @kubo6472,

I already read/saw that. It mentions an /ipfs/ URL. What I'm asking about is an /ipns/ URL. Are you aware of the [difference](https://docs.ipfs.io/concepts/ipns/)? Or did I miss something *`IPNS`* specific on that page?

**Comment by kubo6472** [comment]
Oh, thanks for the link, now I get what you mean. The website itself 
links to this. Dead to me, dunno how you see that appear: 
https://cloudflare-ipfs.com/ipns/12D3KooWB3GY1u6zMLqnf3MJ8zhX3SS1oBj7VXk3xp6sJJiFGZXp

**Comment by pmorch** [comment]
Hmmm. yes, the [documentation](https://github.com/urbanguacamole/torrent-paradise/blob/683aa0cb49fdfe74d33195835bbd271db6ea7a1a/website/ipfs.pug#L6) says this:

>  Address in IPFS is /ipns/12D3KooWB3GY1u6zMLqnf3MJ8zhX3SS1oBj7VXk3xp6sJJiFGZXp in case the domain doesn't work

But

```bash
$ ipfs name resolve 12D3KooWB3GY1u6zMLqnf3MJ8zhX3SS1oBj7VXk3xp6sJJiFGZXp
Error: could not resolve name
```
@urbanguacamole Do you have the private key for that IPNS public key? If not could you create a new one and update `ipfs.pug`?

**Comment by pmorch** [comment]
It looks to me like abandoning the torrent-paradise.ml domain perhaps was done on purpose.

This [commit](https://github.com/urbanguacamole/torrent-paradise/commit/683aa0cb49fdfe74d33195835bbd271db6ea7a1a) changed  README.md to point to https://cloudflare-ipfs.com/ipfs/QmQjsKamNFZRvCMXDvZXQmRYjsmSkmZG5pBCTY4LtMj8hs/about.html  instead of https://torrent-paradise.ml/about.html

**Comment by kubo6472** [comment]
> It looks to me like abandoning the torrent-paradise.ml domain perhaps was done on purpose.
> 
> This [commit](https://github.com/urbanguacamole/torrent-paradise/commit/683aa0cb49fdfe74d33195835bbd271db6ea7a1a) changed README.md to point to https://cloudflare-ipfs.com/ipfs/QmQjsKamNFZRvCMXDvZXQmRYjsmSkmZG5pBCTY4LtMj8hs/about.html instead of https://torrent-paradise.ml/about.html

I think all of us noticed, but since you might not know, this domain is free when prolonged for a year, I own a few of .ml (Mali) domains from the only free, dutch registrar, freenom.com. I experienced a takeover after the domain expired during a "longer that 14 days prolongation grace period's time" I was away from my computer. Nvm, I messaged them, for two months I was thinking it was absolutely lost and then I reported that to abuse contact, which goes back to them. Anyway, as I am writing this, I thought if going of the possibility that someone may be going after torrent paradise through this abuse contact, leaving the domain be might be for the good, since you can't so easily takeout a ipfs/ipns site. I won't be atting the creator, but we all have the code, let's just run things from this repo into some most recent ipfs/ipns version, I will join in peering it, but I have too little experience to actually host it. Would be nice saving the site, since it's so good.

**Comment by julianfairfax** [comment]
I sent @urbanguacamole an email asking if Torrent Paradise was gone for good, and got a reply saying yes.

**Comment by 3unjee** [comment]
snowfl seems to be a decent alternative. Even though it's not IPFS.

**Comment by ProgrammerWhoPrograms** [comment]
> I sent @urbanguacamole an email asking if Torrent Paradise was gone for good, and got a reply saying yes.

Well, the fact that it's on IPFS means that it [still works](ipfs://bafybeibdvh7bkqlh72witdvtk2dndlndj67zgws5rutawenton4qckjjfy/index.html). It's not 'gone'. But it won't be updated again.

**Comment by ProgrammerWhoPrograms** [comment]
> snowfl seems to be a decent alternative. Even though it's not IPFS.

Another one for anime only is [Nyaa](https://nyaa.si/). And of course there's always the Pirate Bay.

**Comment by kubo6472** [comment]
Hey, this issue has long overstayed it's welcome, but we have a good guide in the readme on how to run this ourselves, if anybody's willing to volunteer.

**Comment by julianfairfax** [comment]
> > I sent @urbanguacamole an email asking if Torrent Paradise was gone for good, and got a reply saying yes.
> 
> Well, the fact that it's on IPFS means that it still works. It's not 'gone'. But it won't be updated again.

Neither will the index I think though

**Comment by julianfairfax** [comment]
Since Torrent Paradise is basically dead, as far as I can tell, BTDigg is the only open source torrent site, but since it doesn't have seed counts, I can almost never find a good torrent. Is there a way to "fix" this? If not, are there any other open source torrent search engines? If not, are there any that are actually modern and not filled with ads? It seems Library Genesis has managed to be a modern and ad-free site, since they seem to be treating their work as a public service rather than a commercial endeavour, but it seems this isn't the case for torrent sites? I'd love to be proven wrong.

**Comment by ProgrammerWhoPrograms** [comment]
> If not, are there any other open source torrent search engines? If not, are there any that are actually modern and not filled with ads?

There are some mentioned in this thread. https://snowfl.com and https://nyaa.si. Both pretty snappy (Nyaa more so) and ad-free.

**Comment by ProgrammerWhoPrograms** [comment]
If I close this issue, can I open it again if/when urbunguacamole comes back?

**Comment by julianfairfax** [comment]
> If I close this issue, can I open it again if/when urbunguacamole comes back?

Yes

**Comment by julianfairfax** [comment]
> > If not, are there any other open source torrent search engines? If not, are there any that are actually modern and not filled with ads?
> 
> There are some mentioned in this thread. https://snowfl.com and https://nyaa.si. Both pretty snappy (Nyaa more so) and ad-free.

Yeah I suppose that's true, but snowfl is a metasearch engine and nyaa is for anime. I suppose in that regard, DuckDuckGo and Startpage are also metasearch engines, like snowfl, so it's good they still all exist.
